### ISSUE TITLE
Issue with doubled cache files

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#185]
The code is creating duplicate cache files. Specifically, instead of utilizing the existing cache file named vasprun.xml.cache, a new one with a different identifier, such as vasprun.xml.a45e320a.cache, is being generated. I'm not sure whether this is connected to a recent update in the gemdat or if there is another issue. Is there a way to address this so that the code can utilize the existing cache files instead of creating new ones?

**Comment by v1kko** [comment]
The hash is generated from the arguments to the [`from_vasprun` function](https://github.com/GEMDAT-repos/GEMDAT/blob/9c50918f8abf8478cab2e4c293c0dd6e8edcbd90/src/gemdat/trajectory.py#L158C1-L158C1)

We chose to do this, because when you read in the file in a different way, the cached trajectory might be different. So to make sure that the correct cache is loaded when you try to load the file, a hash of the `kwargs` to the loading function is added to the filename.

If you do not want this, you can specify the `cache` argument to the `from_vasprun` function (to 'my_cache' for example). but beware of the possibility of loading the wrong cache as described above!
