### ISSUE TITLE
Interactive plotting library (especially for 3d plots in notebooks)

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#23]
Currently the plots are created with matplotlib, however for some plots and the dashboard interactivity might be nice to add. We could use
- Altair
- plotly
- bokeh

**Comment by stefsmeets** [comment]
Altair is great for columnar data (dataframes). It lacks other data types that we may want to use. 

Bokeh has a bit more options for different data types, but interactivity is a bit painful, because you have to write the javascript yourself last time I tried.

For molecular plots and movies, we could look at [jsmol](https://jsmol.com/), [stmol](https://github.com/napoles-uach/stmol) / [py3dmol](https://pypi.org/project/py3Dmol/), or [nglview](https://github.com/nglviewer/nglview).

**Comment by v1kko** [comment]
For reference: #83

**Comment by stefsmeets** [comment]
Seems like we have somehow settled on plotly for this. See #177, #174

**Comment by v1kko** [comment]
I think this is done with PR #177 , more can always be added later
